-- 0004_payroll_tables.sql
-- payroll_periods, payroll_lines, payroll_exceptions (spec sections 11, 12, 14).
-- The "Payroll" side of the app. Allocation (0003) feeds this only after
-- leave, cover, employment type, rate and payroll rules are applied — see
-- spec section 2. The actual calculation engine is Phase 4; this migration
-- only lays down the tables it will write to.

create table payroll_periods (
  id uuid primary key default gen_random_uuid(),
  start_date date not null,
  end_date date not null,
  status payroll_period_status not null default 'DRAFT',
  created_by uuid references users (id),
  approved_by uuid references users (id),
  approved_at timestamptz,
  finalised_at timestamptz,
  created_at timestamptz not null default now(),
  constraint payroll_periods_end_after_start check (end_date > start_date),
  constraint payroll_periods_unique_range unique (start_date, end_date)
);

comment on table payroll_periods is 'A fortnightly payroll run. Current working period per spec section 3: 2026-09-07 to 2026-09-20. Not editable after status=FINALISED except via a correction/reversal process (Phase 4).';

create table payroll_lines (
  id uuid primary key default gen_random_uuid(),
  payroll_period_id uuid not null references payroll_periods (id),
  employee_id uuid not null references employees (id),
  payable_hours numeric(7,2),
  leave_hours numeric(7,2),
  cover_hours numeric(7,2),
  hourly_rate numeric(8,2),
  salary_amount numeric(12,2),
  gross_amount numeric(12,2),
  calculation_source text,   -- human-readable trace of how gross_amount was derived, for audit
  status payroll_line_status not null default 'DRAFT',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payroll_lines_unique_employee_per_period unique (payroll_period_id, employee_id)
);

comment on table payroll_lines is 'One row per employee per payroll period — the output of the payroll calculation engine (Phase 4). Never hand-edited; regenerated by calculatePayroll(periodId).';

create table payroll_exceptions (
  id uuid primary key default gen_random_uuid(),
  payroll_period_id uuid not null references payroll_periods (id),
  employee_id uuid references employees (id),
  class_id uuid references classes (id),
  exception_type text not null,
  severity exception_severity not null default 'CRITICAL',
  message text not null,
  resolved boolean not null default false,
  resolved_by uuid references users (id),
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table payroll_exceptions is 'Blocking or advisory issues raised by the payroll engine (e.g. missing rate, unallocated class, inactive employee allocated). A CRITICAL unresolved exception must stop payroll finalisation — see spec section 12. Never auto-resolved by guessing a value.';

create index idx_payroll_lines_period_id on payroll_lines (payroll_period_id);
create index idx_payroll_lines_employee_id on payroll_lines (employee_id);
create index idx_payroll_exceptions_period_id on payroll_exceptions (payroll_period_id);
create index idx_payroll_exceptions_unresolved on payroll_exceptions (payroll_period_id) where resolved = false;
